server:
  port: 10200
spring:
  application:
    name: order-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10050/eureka
    instance-info-replication-interval-seconds: 30
  instance:
    prefer-ip-address: true