server:
  port: 10000

spring:
  application:
    name: zuul-server
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    lettuce:
      shutdown-timeout: 100ms
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10050/eureka
  instance:
    prefer-ip-address: true

zuul:
  # 禁止通过zuul直接访问微服务
  ignored-services: '*'
  # 指定sensitive-headers为空,即放行cookie
  sensitive-headers: Cookie,Authorization
  SendErrorFilter:
    error:
      disable: true
  set-content-length: true
  # 设置调用超时时间
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service
    order-service:
      path: /order/**
      serviceId: order-service

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
